### PR TITLE
Added preliminary support for building for non-AVR platforms

### PR DESCRIPTION
**Pull request by ewasscher**
Added an implementation in C of the functions in avr-libc's util/crc16.h as fallback for non-AVR platforms where the avr-libc version isn't available
Modified enumerators of enum class State in reader.h to avoid collisions with a built-in macro DISABLED of the ESP8266 core for Arduino

### CODE REVIEW

**Comment by ewasscher** [comment]
This should be all changes required for building for most non-AVR platforms (tested for Due, Zero and ESP8266). I plan to create a separate PR for DSMR 2.2 and DMSR 3 support once these changes have been accepted or rejected

**Comment by matthijskooijman** [comment]
I (finally) had a look at your changes, they look good to me. I would like to see a slightly different separation in commits, though. Ideally, you'd have 3 commits:
 - Add CRC implementation for non-AVR platforms (including the license change commit)
 - Rename state members to prevent conflicts on ESP
 - Fix PROGMEM issue on ESP

Each of these are distinct logical changes, so they each deserve their own commit. To get to this point. You should probably reset your branch HEAD (`git reset origin/master`) and then commit each change in turn (using `git add -p` to select what to commit). Then do a force push to your branch on github to update this PR.

**Comment by matthijskooijman** [comment]
It seems the ESP core [removed](https://github.com/esp8266/Arduino/commit/8176cbb28bee2be6a872e2dfdafcababf72ec58a) the DISABLED macro, so perhaps the State constant changes are no longer needed?

**Comment by thomasvnl** [comment]
@matthijskooijman Those conflicts were there a few days ago. Only when using the fork from @ewasscher it worked on an ESP8266.

**Comment by ewasscher** [comment]
@matthijskooijman: could you close the PR without accepting it? I plan on creating a new one the way you requested.

**Pull request closed without merging**
